outputs:
  points:
    description: Points returned by the grading script
    value: "${{ steps.test-json.outputs.points }}"

runs:
  using: composite
  steps:
    - id: test-json
      run: node < "$FORGEJO_ACTION_PATH/index.ts"
      shell: bash